### PR TITLE
Fix Bug: Editing/Adding Tags Resulting in DuplicateEntryException

### LINKED ISSUE #254: Fix Bug: Editing tags should not result in DuplicateEntryException
Additional tasks:
* Add test case.

### PR DESCRIPTION
**Pull request by ChuaPingChan**
Coverage may drop slightly as I added some code. Test for this bug will be added in my test-related PR.

Fix #254

### CODE REVIEW

File: src/main/java/seedu/multitasky/model/entry/EntryList.java [hunk 1]
```diff
@@ -148,6 +149,30 @@ public void updateEntry(ReadOnlyEntry target, ReadOnlyEntry editedEntry)
...
+    private boolean duplicatesPresentAfterEditing(ReadOnlyEntry target, ReadOnlyEntry editedEntry) {
+        ArrayList<Entry> prospectiveInternalList = createInternalListCopyWithoutTarget(target);
+        return prospectiveInternalList.contains(editedEntry);
+    }
+
+    // @@author A0126623L
+    private ArrayList<Entry> createInternalListCopyWithoutTarget(ReadOnlyEntry target) {
+        ArrayList<Entry> copiedInternalList = new ArrayList<Entry>();
+        for (Entry e : internalList) {
+            if (!(e == target)) {
```
Comment (ChuaPingChan) [inline src/main/java/seedu/multitasky/model/entry/EntryList.java]: The `==` operator is used because I'm checking *reference equality*, not *object equality*.

Comment (ChuaPingChan) [inline src/main/java/seedu/multitasky/model/entry/EntryList.java]: The `==` operator is used because I want to compare reference here.

Comment (ChuaPingChan) [inline src/main/java/seedu/multitasky/model/entry/EntryList.java]: Will make the change in the next commit.

**Review by kevinLamKB — APPROVED** [review]

**Comment by ChuaPingChan** [comment]
Ignore Codacy's warning for this PR. `==` is used because I want to check for _reference equality_, not _object equality_.
